// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Block { id: string, course_id: string, block_type: string, week_day: number, start_time: string, end_time: string, location: string, }